name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # for manual publishing retries
    inputs:
      retry-publish:
        description: "Retry publishing"
        type: boolean
        required: false
        default: false

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: leordev/gha-sandbox/releaser@main
        with:
          release-type: go
          go-version: 1.24
          prepare-cmds: |
            go build ./...
